# Generated by Django 2.2.6 on 2019-11-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('datatype', models.CharField(choices=[('b', 'Boolean'), ('i', 'Integer'), ('f', 'Float'), ('c', 'Char'), ('s', 'String'), ('d', 'DateTime')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('actual_date', models.DateTimeField()),
                ('columns', models.ManyToManyField(to='homework1.Column')),
            ],
        ),
    ]
